import type { AISystem } from "@fairhire/api-client";

export const fixtureSystems: AISystem[] = [
  {
    id: "sys-talentrank",
    organization_id: "org-northstar",
    name: "TalentRank EU",
    purpose: "Candidate scoring",
    lifecycle_status: "active",
    release_status: "review_required",
    provider_type: "internal",
    provider_name: null,
    jurisdictions: ["EU", "DE", "FR", "NL"],
    owner_name: "Maya Chen",
    next_review_at: "2026-09-03T09:00:00Z",
    assessment_version: 3,
  },
  {
    id: "sys-cvlens",
    organization_id: "org-northstar",
    name: "CV Lens",
    purpose: "Resume reading",
    lifecycle_status: "active",
    release_status: "approved",
    provider_type: "third_party",
    provider_name: "Asteria ATS",
    jurisdictions: ["EU"],
    owner_name: "Ana Silva",
    next_review_at: "2026-11-15T09:00:00Z",
    assessment_version: 2,
  },
  {
    id: "sys-interviewsense",
    organization_id: "org-northstar",
    name: "InterviewSense EU",
    purpose: "Video interview review",
    lifecycle_status: "trial",
    release_status: "blocked",
    provider_type: "third_party",
    provider_name: "Outside supplier",
    jurisdictions: ["DE"],
    owner_name: "Ana Silva",
    next_review_at: "2026-09-01T13:00:00Z",
    assessment_version: 1,
  },
  {
    id: "sys-rolematch",
    organization_id: "org-northstar",
    name: "RoleMatch",
    purpose: "Job recommendation",
    lifecycle_status: "active",
    release_status: "approved",
    provider_type: "internal",
    provider_name: null,
    jurisdictions: ["EU"],
    owner_name: "Jon Bell",
    next_review_at: "2026-12-01T09:00:00Z",
    assessment_version: 4,
  },
];
