import type {
  AISystem,
  Approval,
  FindingDetail,
  ReleaseGate,
} from "@fairhire/api-client";

export const fixtureSystems: AISystem[] = [
  {
    id: "sys-talentrank",
    organization_id: "org-northstar",
    name: "TalentRank EU",
    purpose: "Candidate scoring",
    lifecycle_status: "active",
    release_status: "review_required",
    provider_type: "internal",
    provider_name: null,
    jurisdictions: ["EU", "DE", "FR", "NL"],
    owner_name: "Maya Chen",
    next_review_at: "2026-09-03T09:00:00Z",
    assessment_version: 3,
    organization_roles: ["provider", "deployer"],
    profiling: true,
    solely_automated: false,
  },
  {
    id: "sys-cvlens",
    organization_id: "org-northstar",
    name: "CV Lens",
    purpose: "Resume reading",
    lifecycle_status: "active",
    release_status: "approved",
    provider_type: "third_party",
    provider_name: "Asteria ATS",
    jurisdictions: ["EU"],
    owner_name: "Ana Silva",
    next_review_at: "2026-11-15T09:00:00Z",
    assessment_version: 2,
    organization_roles: ["deployer"],
    profiling: false,
    solely_automated: false,
  },
  {
    id: "sys-interviewsense",
    organization_id: "org-northstar",
    name: "InterviewSense EU",
    purpose: "Video interview review",
    lifecycle_status: "trial",
    release_status: "blocked",
    provider_type: "third_party",
    provider_name: "Outside supplier",
    jurisdictions: ["DE"],
    owner_name: "Ana Silva",
    next_review_at: "2026-09-01T13:00:00Z",
    assessment_version: 1,
    organization_roles: ["deployer"],
    profiling: true,
    solely_automated: false,
  },
  {
    id: "sys-rolematch",
    organization_id: "org-northstar",
    name: "RoleMatch",
    purpose: "Job recommendation",
    lifecycle_status: "active",
    release_status: "approved",
    provider_type: "internal",
    provider_name: null,
    jurisdictions: ["EU"],
    owner_name: "Jon Bell",
    next_review_at: "2026-12-01T09:00:00Z",
    assessment_version: 4,
    organization_roles: ["provider", "deployer"],
    profiling: false,
    solely_automated: false,
  },
];

export const fixtureFindings: FindingDetail[] = [
  {
    id: "fnd-104",
    organization_id: "org-northstar",
    ai_system_id: "sys-talentrank",
    audit_run_id: "run-2841",
    source_metric_id: "metric-dp-gender",
    title: "Career gaps may reduce selection for women",
    description:
      "Matched-pair evidence and output sensitivity both indicate that career-gap duration can reduce selection scores for similarly qualified candidates.",
    severity: "high",
    confidence: "high",
    affected_groups: ["Women returning to work"],
    evidence_refs: ["AR-2841 / proxy-07", "AR-2841 / cf-12"],
    control_refs: ["POL-FR-02 §4.2", "EU AI Act Article 10"],
    recommended_control:
      "Remove the career-gap feature, retrain, and rerun the approved fairness strategy.",
    owner_id: "maya.chen@fairhire.test",
    owner_name: "Maya Chen",
    due_at: "2026-09-05T16:00:00Z",
    status: "mitigating",
    residual_risk: null,
    acceptance_reason: null,
    accepted_by: null,
    accepted_at: null,
    accepted_until: null,
    created_by: "elias.roth@fairhire.test",
    created_at: "2026-08-28T10:12:00Z",
    updated_at: "2026-09-02T14:30:00Z",
    tasks: [
      {
        id: "tsk-104-a",
        organization_id: "org-northstar",
        finding_id: "fnd-104",
        title: "Remove career-gap duration and retrain",
        description: "Bind the replacement model and code review to this task.",
        owner_id: "jon.bell@fairhire.test",
        owner_name: "Jon Bell",
        due_at: "2026-09-02T16:00:00Z",
        status: "in_progress",
        evidence_refs: [],
        completed_at: null,
        created_by: "maya.chen@fairhire.test",
        created_at: "2026-08-29T09:00:00Z",
        updated_at: "2026-09-02T08:45:00Z",
      },
    ],
    retests: [],
  },
  {
    id: "fnd-097",
    organization_id: "org-northstar",
    ai_system_id: "sys-interviewsense",
    audit_run_id: "run-2798",
    title: "Emotion analysis may be a prohibited employment use",
    description:
      "The vendor materials describe emotion inference during interviews. Deployment remains blocked pending legal classification and removal evidence.",
    severity: "critical",
    confidence: "high",
    affected_groups: ["All interviewed candidates"],
    evidence_refs: ["Vendor dossier / p.18", "Assessment v1 / Q-07"],
    control_refs: ["EU AI Act Article 5(1)(f)", "POL-AI-01 §2.1"],
    recommended_control:
      "Disable emotion inference and obtain a vendor attestation before any further trial.",
    owner_id: "ana.silva@fairhire.test",
    owner_name: "Ana Silva",
    due_at: "2026-09-03T16:00:00Z",
    status: "triaged",
    residual_risk: null,
    acceptance_reason: null,
    accepted_by: null,
    accepted_at: null,
    accepted_until: null,
    created_by: "maya.chen@fairhire.test",
    created_at: "2026-08-25T11:00:00Z",
    updated_at: "2026-09-01T09:20:00Z",
    tasks: [],
    retests: [],
  },
  {
    id: "fnd-105",
    organization_id: "org-northstar",
    ai_system_id: "sys-talentrank",
    audit_run_id: "run-2841",
    title: "Later-stage outcome labels remain incomplete",
    description:
      "Hiring outcome coverage is below the approved evidence threshold, limiting equal-opportunity conclusions.",
    severity: "medium",
    confidence: "medium",
    affected_groups: ["All applicants"],
    evidence_refs: ["AR-2841 / data-quality-03"],
    control_refs: ["POL-DATA-04 §3.3"],
    recommended_control:
      "Complete outcome linkage and rerun label-dependent tests.",
    owner_id: "elias.roth@fairhire.test",
    owner_name: "Elias Roth",
    due_at: "2026-09-18T16:00:00Z",
    status: "open",
    residual_risk: null,
    acceptance_reason: null,
    accepted_by: null,
    accepted_at: null,
    accepted_until: null,
    created_by: "platform",
    created_at: "2026-09-01T07:20:00Z",
    updated_at: "2026-09-01T07:20:00Z",
    tasks: [],
    retests: [],
  },
];

export const fixtureApprovals: Approval[] = [
  {
    id: "apr-rai-4",
    organization_id: "org-northstar",
    ai_system_id: "sys-talentrank",
    chain_version: 4,
    stage: "responsible_ai",
    sequence: 1,
    decision: "approved",
    approver_id: "maya.chen@fairhire.test",
    approver_name: "Maya Chen",
    reason: "Audit scope and test strategy reviewed.",
    decided_at: "2026-09-02T10:00:00Z",
    expires_at: "2026-12-02T10:00:00Z",
    created_by: "maya.chen@fairhire.test",
    created_at: "2026-09-02T09:30:00Z",
  },
  {
    id: "apr-hr-4",
    organization_id: "org-northstar",
    ai_system_id: "sys-talentrank",
    chain_version: 4,
    stage: "hr",
    sequence: 2,
    decision: "pending",
    approver_id: null,
    approver_name: null,
    reason: null,
    decided_at: null,
    expires_at: null,
    created_by: "maya.chen@fairhire.test",
    created_at: "2026-09-02T09:30:00Z",
  },
  {
    id: "apr-legal-4",
    organization_id: "org-northstar",
    ai_system_id: "sys-talentrank",
    chain_version: 4,
    stage: "legal_dpo",
    sequence: 3,
    decision: "pending",
    approver_id: null,
    approver_name: null,
    reason: null,
    decided_at: null,
    expires_at: null,
    created_by: "maya.chen@fairhire.test",
    created_at: "2026-09-02T09:30:00Z",
  },
];

export const fixtureReleaseGates: Record<string, ReleaseGate> = {
  "sys-talentrank": {
    ai_system_id: "sys-talentrank",
    status: "review_required",
    chain_version: 4,
    required_stages: ["responsible_ai", "hr", "legal_dpo"],
    approved_stages: ["responsible_ai"],
    blockers: [],
    evaluated_at: "2026-09-03T08:00:00Z",
  },
  "sys-interviewsense": {
    ai_system_id: "sys-interviewsense",
    status: "blocked",
    chain_version: null,
    required_stages: ["responsible_ai", "hr", "legal_dpo"],
    approved_stages: [],
    blockers: [
      {
        code: "critical_finding",
        message:
          "Critical finding is not resolved or covered by a valid exception.",
        resource_id: "fnd-097",
      },
    ],
    evaluated_at: "2026-09-03T08:00:00Z",
  },
};
