/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/ai-systems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ai Systems */
        get: operations["list_ai_systems_v1_ai_systems_get"];
        put?: never;
        /** Create Ai System */
        post: operations["create_ai_system_v1_ai_systems_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session */
        get: operations["session_v1_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AISystemCreate */
        AISystemCreate: {
            /** Jurisdictions */
            jurisdictions: string[];
            /**
             * Lifecycle Status
             * @default draft
             * @enum {string}
             */
            lifecycle_status: "draft" | "trial" | "active" | "retired";
            /** Name */
            name: string;
            /** Next Review At */
            next_review_at?: string | null;
            /** Owner Name */
            owner_name: string;
            /** Provider Name */
            provider_name?: string | null;
            /**
             * Provider Type
             * @enum {string}
             */
            provider_type: "internal" | "third_party";
            /** Purpose */
            purpose: string;
            /**
             * Release Status
             * @default draft
             * @enum {string}
             */
            release_status: "approved" | "review_required" | "blocked" | "draft" | "insufficient_evidence";
        };
        /** AISystemListResponse */
        AISystemListResponse: {
            /** Items */
            items: components["schemas"]["AISystemResponse"][];
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Page Size
             * @default 25
             */
            page_size: number;
            /** Total */
            total: number;
        };
        /** AISystemResponse */
        AISystemResponse: {
            /** Assessment Version */
            assessment_version: number;
            /** Id */
            id: string;
            /** Jurisdictions */
            jurisdictions: string[];
            /**
             * Lifecycle Status
             * @default draft
             * @enum {string}
             */
            lifecycle_status: "draft" | "trial" | "active" | "retired";
            /** Name */
            name: string;
            /** Next Review At */
            next_review_at?: string | null;
            /** Organization Id */
            organization_id: string;
            /** Owner Name */
            owner_name: string;
            /** Provider Name */
            provider_name?: string | null;
            /**
             * Provider Type
             * @enum {string}
             */
            provider_type: "internal" | "third_party";
            /** Purpose */
            purpose: string;
            /**
             * Release Status
             * @default draft
             * @enum {string}
             */
            release_status: "approved" | "review_required" | "blocked" | "draft" | "insufficient_evidence";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "admin" | "responsible_ai" | "hr_reviewer" | "legal_reviewer" | "model_developer" | "auditor" | "procurement";
        /** SessionResponse */
        SessionResponse: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /** Organization Id */
            organization_id: string;
            /** Organization Name */
            organization_name: string;
            /** Permissions */
            permissions: string[];
            role: components["schemas"]["Role"];
            /** User Id */
            user_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_ai_systems_v1_ai_systems_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: {
                "X-Organization-ID"?: string | null;
                "X-Dev-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AISystemListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_ai_system_v1_ai_systems_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Organization-ID"?: string | null;
                "X-Dev-User"?: string | null;
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AISystemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AISystemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    session_v1_session_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Organization-ID"?: string | null;
                "X-Dev-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
